id: AC890E654
title: A Brief Ritual for Consecrating Representations of Enlightened Body, Speech
  and Mind
type: translation
pechas:
- I99499495
- I4F13A0E7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:42:44.997156
  last_modified_at: 2023-01-04 11:42:44.997168
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I99499495/BC4E: '6295'
  I4F13A0E7/5091: '6295'
